extends: recommended

ENABLE_LINTERS:
  - TYPESCRIPT_ESLINT
  - JAVASCRIPT_ESLINT
  - JSON_JSONLINT
  - YAML_YAMLLINT
  - MARKDOWN_MARKDOWNLINT
  - GIT_GIT_DIFF

DISABLE_LINTERS:
  - COPYPASTE_JSCPD

FAIL_FAST: false
